org: rjgallac
app: aws-serverless-sqs-project
service: aws-serverless-sqs-project
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  region: eu-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:*
      Resource:
        - arn:aws:sqs:eu-west-2:273521126402:MyQueue
functions:
  addMessage:
    handler: src/addMessage.handler
    events:
      - httpApi:
          path: /message
          method: post    
  fetchMessages:
    handler: src/fetchMessages.handler
    events:
      - httpApi:
          path: /message
          method: get

# plugins:
#   - serverless-webpack

package:
  individually: true
	
resources:
  Resources:
    MyQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "MyQueue"
